CREATE TABLE VILLAGE_BK AS
SELECT *
FROM VILLAGE WITH NO DATA;


INSERT INTO VILLAGE
SELECT V2.ID
     , V2.NAME
FROM VILLAGE_BK V2
WHERE NOT EXISTS (
    SELECT 'X'
      FROM VILLAGE V1
     WHERE V1.ID = V2.ID );

DELETE FROM VILLAGE_BK WHERE ID = 401;


SELECT *
FROM VILLAGE;